#!/usr/bin/python
import argparse
from SecretManager import SecretManager
parser = argparse.ArgumentParser(description='Delivers Secret to Authorized Personnal')
parser.add_argument('--getSecret', help='fetches secret if you know the word', required=False)
arguments = parser.parse_args()
if arguments.getSecret != None and arguments.getSecret !="":
	print arguments.getSecret
	print SecretManager(arguments.getSecret).get_secret()
else:
	print "ERROR : SecretAgent must be told Secret Word with --getSecret option"
	print "For more Info type SecretAgent --help"





